import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e5e2e1",
        "error": "#ffb4ab",
        "secondary-container": "#3891fe",
        "on-tertiary-fixed": "#001a41",
        "tertiary-fixed": "#d8e2ff",
        "outline": "#a68a8a",
        "outline-variant": "#574142",
        "secondary": "#a8c8ff",
        "on-surface-variant": "#debfbf",
        "surface-variant": "#353534",
        "inverse-on-surface": "#313030",
        "secondary-fixed": "#d5e3ff",
        "on-primary": "#680017",
        "inverse-primary": "#aa3340",
        "on-background": "#e5e2e1",
        "surface-container-high": "#2a2a2a",
        "surface-container-lowest": "#0e0e0e",
        "surface-tint": "#ffb3b5",
        "surface-bright": "#3a3939",
        "on-secondary-fixed-variant": "#00468a",
        "on-surface": "#e5e2e1",
        "surface-container": "#201f1f",
        "secondary-fixed-dim": "#a8c8ff",
        "primary-fixed-dim": "#ffb3b5",
        "on-error": "#690005",
        "surface-container-highest": "#353534",
        "on-secondary-container": "#002955",
        "on-secondary": "#003061",
        "on-tertiary-fixed-variant": "#004493",
        "surface": "#131313",
        "surface-dim": "#131313",
        "on-tertiary-container": "#003473",
        "primary": "#ffb3b5",
        "tertiary-fixed-dim": "#adc7ff",
        "background": "#131313",
        "on-secondary-fixed": "#001b3c",
        "on-primary-container": "#72031c",
        "on-primary-fixed": "#40000b",
        "on-error-container": "#ffdad6",
        "tertiary": "#adc7ff",
        "surface-container-low": "#1c1b1b",
        "primary-fixed": "#ffdada",
        "primary-container": "#ff727c",
        "tertiary-container": "#699eff",
        "on-tertiary": "#002e68",
        "on-primary-fixed-variant": "#89192a",
        "error-container": "#93000a",
      },
      fontFamily: {
        headline: ["Epilogue", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      backgroundImage: {
        "primary-gradient": "linear-gradient(135deg, #ffb3b5, #ff727c)",
      },
    },
  },
  plugins: [],
};

export default config;
