import dotenv from "dotenv";
dotenv.config({ path: ".env.local", override: true });

import { PrismaClient, ScrapeType, SourceCategory } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const sources = [
  // ── Aggregators ──────────────────────────────────────────────────────────
  {
    slug: "foopee",
    name: "Foopee Punk List",
    url: "https://foopee.com/punk/the-list/",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.AGGREGATOR,
    enabled: true,
  },
  {
    slug: "19hz",
    name: "19hz Bay Area",
    url: "https://19hz.info/eventlisting_BayArea.php",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.AGGREGATOR,
    enabled: true,
  },
  {
    slug: "funcheap",
    name: "Funcheap SF",
    url: "https://sf.funcheap.com/",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.AGGREGATOR,
    enabled: true,
  },
  {
    slug: "timeout",
    name: "Timeout San Francisco",
    url: "https://www.timeout.com/san-francisco/things-to-do",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.AGGREGATOR,
    enabled: false,
  },
  {
    slug: "sflive",
    name: "SF Live",
    url: "https://sflive.art",
    scrapeType: ScrapeType.API,
    category: SourceCategory.AGGREGATOR,
    enabled: true,
  },
  {
    slug: "residentadvisor",
    name: "Resident Advisor SF",
    url: "https://ra.co/events/us/sanfrancisco",
    scrapeType: ScrapeType.PLAYWRIGHT,
    category: SourceCategory.AGGREGATOR,
    enabled: true,
  },
  {
    slug: "partiful",
    name: "Partiful",
    url: "https://partiful.com/explore/sf",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.AGGREGATOR,
    enabled: true,
  },
  {
    slug: "luma",
    name: "Luma SF",
    url: "https://lu.ma/sf",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.AGGREGATOR,
    enabled: true,
  },
  {
    slug: "songkick",
    name: "Songkick",
    url: "https://www.songkick.com",
    scrapeType: ScrapeType.API,
    category: SourceCategory.AGGREGATOR,
    enabled: false,
  },
  {
    slug: "eventbrite",
    name: "Eventbrite",
    url: "https://www.eventbrite.com/d/ca--san-francisco/events/",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.AGGREGATOR,
    enabled: true,
  },
  {
    slug: "meetup",
    name: "Meetup",
    url: "https://www.meetup.com",
    scrapeType: ScrapeType.API,
    category: SourceCategory.AGGREGATOR,
    enabled: false,
  },
  {
    slug: "posh",
    name: "Posh",
    url: "https://posh.vip/explore",
    scrapeType: ScrapeType.API,
    category: SourceCategory.AGGREGATOR,
    enabled: true,
  },
  {
    slug: "bandsintown",
    name: "Bandsintown SF",
    url: "https://www.bandsintown.com/c/san-francisco-ca",
    scrapeType: ScrapeType.PLAYWRIGHT,
    category: SourceCategory.AGGREGATOR,
    enabled: true,
  },
  {
    slug: "tixr",
    name: "Tixr SF",
    url: "https://www.tixr.com/search?q=san+francisco",
    scrapeType: ScrapeType.PLAYWRIGHT,
    category: SourceCategory.AGGREGATOR,
    enabled: false, // DataDome bot protection blocks all automated access (403 + CAPTCHA)
  },
  {
    slug: "kqed",
    name: "KQED Live Events",
    url: "https://www.kqed.org/events",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.AGGREGATOR,
    enabled: true,
  },
  {
    slug: "dothebay",
    name: "DoTheBay",
    url: "https://dothebay.com/events",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.AGGREGATOR,
    enabled: true,
  },
  {
    slug: "brokeassstuart",
    name: "Broke Ass Stuart (DoTheBay)",
    url: "https://brokeassstuart.dothebay.com/events",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.AGGREGATOR,
    enabled: true,
  },
  {
    slug: "instagram",
    name: "Instagram Venues",
    url: "https://www.instagram.com",
    scrapeType: ScrapeType.API,
    category: SourceCategory.AGGREGATOR,
    enabled: true,
  },
  {
    slug: "decentered",
    name: "Decentered",
    url: "https://events.decentered.org/",
    scrapeType: ScrapeType.API,
    category: SourceCategory.AGGREGATOR,
    enabled: true,
  },
  // ── Venue sites ──────────────────────────────────────────────────────────
  {
    slug: "storkclub",
    name: "Thee Stork Club",
    url: "https://theestorkclub.com/calendar/",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.VENUE,
    enabled: true,
  },
  {
    slug: "borderlandsbooks",
    name: "Borderlands Books",
    url: "https://borderlands-books.com/v2/events/",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.VENUE,
    enabled: true,
  },
  {
    slug: "greenapplebooks",
    name: "Green Apple Books",
    url: "https://greenapplebooks.com/events",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.VENUE,
    enabled: true,
  },
  {
    slug: "medicine-for-nightmares",
    name: "Medicine for Nightmares",
    url: "https://medicinefornightmares.com/events",
    scrapeType: ScrapeType.API,
    category: SourceCategory.VENUE,
    enabled: true,
  },
  {
    slug: "omnivorebooks",
    name: "Omnivore Books on Food",
    url: "https://omnivorebooks.myshopify.com/collections/upcoming-events",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.VENUE,
    enabled: true,
  },
  {
    slug: "noe-valley-town-square",
    name: "Noe Valley Town Square",
    url: "https://noevalleytownsquare.com/events",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.VENUE,
    enabled: true,
  },
  {
    slug: "citylights",
    name: "City Lights Books",
    url: "https://citylights.com/events/",
    scrapeType: ScrapeType.PLAYWRIGHT,
    category: SourceCategory.VENUE,
    enabled: true,
  },
  {
    slug: "sfjazz",
    name: "SFJAZZ",
    url: "https://www.sfjazz.org/calendar/",
    scrapeType: ScrapeType.PLAYWRIGHT,
    category: SourceCategory.VENUE,
    enabled: true,
  },
  {
    slug: "sfspca",
    name: "SF SPCA",
    url: "https://www.sfspca.org/events/list/",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.INSTITUTIONAL,
    enabled: true,
  },
  {
    slug: "fortmason",
    name: "Fort Mason Center",
    url: "https://fortmason.org/events/",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.VENUE,
    enabled: true,
  },
  {
    slug: "assemblepuzzlery",
    name: "Assemble Puzzlery",
    url: "https://assemblepuzzlery.com/pages/events",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.VENUE,
    enabled: true,
  },
  {
    slug: "uctheatre",
    name: "The UC Theatre",
    url: "https://www.theuctheatre.org/",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.VENUE,
    enabled: true,
  },
  {
    slug: "greatstartheater",
    name: "Great Star Theater",
    url: "https://www.greatstartheater.org/whats-playing",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.VENUE,
    enabled: true,
  },
  {
    slug: "cityboxoffice",
    name: "City Box Office",
    url: "https://www.cityboxoffice.com/performancelisting.asp",
    scrapeType: ScrapeType.API,
    category: SourceCategory.VENUE,
    enabled: true,
  },
  {
    slug: "civickitchen",
    name: "Civic Kitchen SF",
    url: "https://www.civickitchensf.com/classes-and-events/",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.VENUE,
    enabled: true,
  },
  {
    slug: "churchofclown",
    name: "Church of Clown",
    url: "https://www.churchofclown.org/events",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.VENUE,
    enabled: true,
  },
  // ── Institutional ────────────────────────────────────────────────────────
  {
    slug: "usfca",
    name: "USF Community Events",
    url: "https://myusf.usfca.edu/calendar?field_category%5B2456%5D=2456",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.INSTITUTIONAL,
    enabled: true,
  },
  {
    slug: "sfpl",
    name: "SF Public Library",
    url: "https://sfpl.org/events",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.INSTITUTIONAL,
    enabled: true,
  },
  {
    slug: "sfrecpark",
    name: "SF Recreation & Parks",
    url: "https://sfrecpark.org/Calendar.aspx",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.INSTITUTIONAL,
    enabled: true,
  },
  {
    slug: "exploratorium",
    name: "Exploratorium",
    url: "https://www.exploratorium.edu/visit/calendar",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.INSTITUTIONAL,
    enabled: true,
  },
  // ── Community ────────────────────────────────────────────────────────────
  {
    slug: "reddit-sfevents",
    name: "Reddit r/SFEvents",
    url: "https://www.reddit.com/r/SFEvents/",
    scrapeType: ScrapeType.API,
    category: SourceCategory.COMMUNITY,
    enabled: true,
  },
  {
    slug: "badslava",
    name: "Badslava SF Trivia Nights",
    url: "https://badslava.com/san-francisco-trivia-nights.php",
    scrapeType: ScrapeType.CHEERIO,
    category: SourceCategory.COMMUNITY,
    enabled: true,
  },
  {
    slug: "community",
    name: "Community Submissions",
    url: "https://happening.app",
    scrapeType: ScrapeType.MANUAL,
    category: SourceCategory.COMMUNITY,
    enabled: true,
  },
];

async function main() {
  console.log("Seeding sources...");
  for (const source of sources) {
    await prisma.source.upsert({
      where: { slug: source.slug },
      update: source,
      create: source,
    });
    console.log(`  ✓ ${source.name}`);
  }
  console.log("Done.");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
