export const dynamic = "force-dynamic";

import type { Metadata } from "next";
import { notFound, permanentRedirect } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { CATEGORY_LABELS, CATEGORY_COLORS } from "@/lib/types";
import { proxiedImage, resolveFallbackImage } from "@/lib/eventImage";
import { formatDateLongSF, formatTimeSF, formatDateShortSF } from "@/lib/sfDate";
import { Clock, MapPin, ExternalLink, CalendarPlus, Star } from "lucide-react";
import FeaturedToggle from "@/app/admin/submissions/FeaturedToggle";
import BackButton from "./BackButton";
import ShareButton from "./ShareButton";
import ReportButton from "./ReportButton";
import InterestButton from "@/components/events/InterestButton";
import FollowButton from "@/components/events/FollowButton";
import EventFlyerContainer from "./EventFlyerContainer";
import VenueMiniMapWrapper from "@/components/map/VenueMiniMapWrapper";
import EventEditPanel from "./EventEditPanel";
import { getSessionUser } from "@/lib/auth";
import { serviceAreaTBACity } from "@/lib/venues";
import { Prisma } from "@prisma/client";

/** Extract a venue hint from a title like "...at Ocean Beach" or "...in Golden Gate Park" */
function extractLocationFromTitle(title: string): string | null {
  const match = title.match(/\b(?:at|in)\s+([a-z][a-z\s']+?)(?:\s+on\b|\s+this\b|\s*$)/i);
  if (!match) return null;
  const candidate = match[1].trim();
  // Skip generic/short phrases
  if (candidate.split(" ").length < 2 && candidate.length < 6) return null;
  return candidate.replace(/\b\w/g, (c) => c.toUpperCase());
}

async function getEvent(id: string) {
  return prisma.event.findUnique({
    where: { id },
    include: {
      source: { select: { slug: true, name: true, url: true } },
      _count: { select: { interests: true } },
    },
  });
}

async function getSimilarEvents(event: NonNullable<Awaited<ReturnType<typeof getEvent>>>) {
  return prisma.event.findMany({
    where: {
      id: { not: event.id },
      startDate: { gte: new Date() },
      OR: [
        { category: event.category ?? undefined },
        { neighborhood: event.neighborhood ?? undefined },
      ],
    },
    take: 3,
    orderBy: { startDate: "asc" },
    select: {
      id: true,
      title: true,
      startDate: true,
      imageUrl: true,
      category: true,
      venueName: true,
    },
  });
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;
  const event = await getEvent(id);
  // Non-published events aren't public — don't emit share/OG metadata for them.
  if (!event || event.status !== "PUBLISHED") return {};

  const dateLabel = formatDateLongSF(event.startDate);
  const venueDisplayName = event.venueName ?? extractLocationFromTitle(event.title);

  const parts = [event.allDay ? dateLabel : `${dateLabel} at ${formatTimeSF(event.startDate)}`];
  if (venueDisplayName) parts.push(venueDisplayName);
  if (event.neighborhood) parts.push(event.neighborhood);
  if (event.description) parts.push(event.description.slice(0, 120).trim());
  const description = parts.join(" · ");

  const title = `${event.title} — happening`;

  // The share image is the branded card generated by ./opengraph-image and
  // ./twitter-image — Next injects the og:image / twitter:image tags from those
  // file conventions, so we deliberately don't set `images` here (doing so would
  // advertise the raw flyer alongside the card and let crawlers pick the flyer).
  return {
    title,
    description,
    openGraph: {
      title,
      description,
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
  };
}

export default async function EventDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const sessionUser = await getSessionUser();
  // Inline editing is for staff only. Since open signup (#96) made USER the
  // default role, !!sessionUser is no longer an editor check — gate on the role.
  const isEditor = sessionUser?.role === "ADMIN" || sessionUser?.role === "EDITOR";
  const isSignedIn = !!sessionUser;
  const isAdmin = sessionUser?.role === "ADMIN";
  const event = await getEvent(id);
  if (!event) notFound();

  // This event was merged into a canonical duplicate — send visitors there.
  if (event.status === "ARCHIVED" && event.mergedIntoId) {
    permanentRedirect(`/events/${event.mergedIntoId}`);
  }

  // Only PUBLISHED events are public. Staff (editors/admins) can still preview any
  // status to review submissions, rejects, and holds; everyone else gets a 404 so
  // rejected/pending/trashed events aren't reachable by direct link.
  if (event.status !== "PUBLISHED" && !isEditor) {
    notFound();
  }

  const similar = await getSimilarEvents(event);

  // Which of this event's followable targets the signed-in user already follows,
  // so each FollowButton renders in the right initial state (issue #98). Artists
  // are keyed lowercase to match how follows are stored (lib/artistMatch).
  const performerNames = [...new Set(event.performers.map((p) => p.toLowerCase()))];
  const followedKeys = new Set<string>();
  if (sessionUser) {
    const orConds: Prisma.FollowWhereInput[] = [];
    if (event.category) orConds.push({ targetType: "CATEGORY", targetId: event.category });
    if (event.venueId) orConds.push({ targetType: "VENUE", targetId: event.venueId });
    if (performerNames.length) orConds.push({ targetType: "ARTIST", targetId: { in: performerNames } });
    if (orConds.length) {
      const rows = await prisma.follow.findMany({
        where: { userId: sessionUser.id, OR: orConds },
        select: { targetType: true, targetId: true },
      });
      for (const r of rows) followedKeys.add(`${r.targetType}:${r.targetId}`);
    }
  }
  const isFollowing = (type: string, id: string) => followedKeys.has(`${type}:${id}`);

  const categoryLabel = event.category ? CATEGORY_LABELS[event.category] : null;
  const categoryColor = event.category ? CATEGORY_COLORS[event.category] : "#3a3a3a";
  const fallbackImage = resolveFallbackImage({
    venueName: event.venueName,
    sourceSlug: event.source.slug,
    category: event.category,
  });
  const proxiedImageUrl = proxiedImage(event.imageUrl);
  const dateLabel = formatDateLongSF(event.startDate);
  const timeLabel = event.allDay ? null : formatTimeSF(event.startDate);
  const endTimeLabel = !event.allDay && event.endDate ? formatTimeSF(event.endDate) : null;
  // Location-TBA events (secret-location raves, venue not yet announced) carry a
  // placeholder venueName and no coords. Show a "location TBA" callout instead of
  // the raw placeholder, and suppress the maps link (it would just search the
  // placeholder string).
  const tbaCity = serviceAreaTBACity(event.venueName);
  const venueDisplayName = event.venueName ?? extractLocationFromTitle(event.title);
  const mapsQuery = tbaCity
    ? null
    : event.venueAddress ?? (venueDisplayName ? `${venueDisplayName}, San Francisco, CA` : null);

  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL ?? "https://happeningsf.now";

  const jsonLd: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": "Event",
    name: event.title,
    startDate: event.startDate.toISOString(),
    ...(event.endDate ? { endDate: event.endDate.toISOString() } : {}),
    eventStatus: "https://schema.org/EventScheduled",
    eventAttendanceMode: "https://schema.org/OfflineEventAttendanceMode",
    url: `${baseUrl}/events/${event.id}`,
    ...(event.imageUrl ? { image: [event.imageUrl] } : {}),
    ...(event.description ? { description: event.description } : {}),
    location: {
      "@type": "Place",
      name: venueDisplayName ?? "San Francisco",
      address: {
        "@type": "PostalAddress",
        addressLocality: event.city,
        addressRegion: "CA",
        addressCountry: "US",
        ...(event.venueAddress ? { streetAddress: event.venueAddress } : {}),
      },
      ...(event.latitude && event.longitude
        ? { geo: { "@type": "GeoCoordinates", latitude: event.latitude, longitude: event.longitude } }
        : {}),
    },
    organizer: {
      "@type": "Organization",
      name: event.source.name,
      url: event.source.url,
    },
    offers: {
      "@type": "Offer",
      url: event.sourceUrl,
      ...(event.isFree
        ? { price: "0", priceCurrency: "USD", availability: "https://schema.org/InStock" }
        : event.price
          ? { price: event.price.replace(/^\$/, ""), priceCurrency: "USD" }
          : {}),
    },
    ...(event.performers.length > 0
      ? {
          performer: event.performers.map((p) => ({
            "@type": "PerformingGroup",
            name: p,
          })),
        }
      : {}),
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
    <div className="max-w-screen-xl mx-auto px-4 sm:px-6 py-6 sm:py-8">
      {/* Admin bar */}
      {isAdmin && (
        <div className="mb-4 flex items-center gap-3 bg-surface-container-high rounded-xl px-4 py-3">
          <span className="font-body text-xs text-on-surface-variant">admin</span>
          <FeaturedToggle id={event.id} featured={event.featured} />
        </div>
      )}

      {/* Editor bar */}
      {isEditor && <EventEditPanel event={event} />}

      {/* Back nav */}
      <div className="flex items-center justify-between mb-8">
        <BackButton />
        <ShareButton title={event.title} />
      </div>

      {/* Main grid: flyer left, details right */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 lg:gap-12 mb-12 lg:mb-16">
        {/* Flyer */}
        <EventFlyerContainer
          proxiedImageUrl={proxiedImageUrl}
          fallbackImage={fallbackImage}
          categoryColor={categoryColor}
          title={event.title}
          categoryLabel={categoryLabel}
          tags={event.tags}
        />

        {/* Details */}
        <div className="flex flex-col">
          {/* Category + neighborhood chips */}
          <div className="flex flex-wrap gap-2 mb-4">
            {categoryLabel && (
              <span
                className="chip"
                style={{ background: `${categoryColor}22`, color: categoryColor }}
              >
                {categoryLabel}
              </span>
            )}
            {event.neighborhood && (
              <span className="chip">{event.neighborhood}</span>
            )}
            <span className="chip text-on-surface-variant">{event.source.name}</span>
            {event.category && categoryLabel && (
              <FollowButton
                targetType="CATEGORY"
                targetId={event.category}
                label={categoryLabel}
                isSignedIn={isSignedIn}
                initialFollowing={isFollowing("CATEGORY", event.category)}
              />
            )}
          </div>

          {/* Title */}
          <h1 className="font-headline font-black text-4xl lg:text-5xl text-on-surface lowercase leading-tight mb-6">
            {event.title}
          </h1>

          {/* Date / time / price */}
          <div className="flex flex-wrap gap-3 mb-6">
            <span className="bg-surface-container rounded-DEFAULT px-3 py-1.5 text-xs font-body text-on-surface flex items-center gap-1.5">
              <Clock size={12} className="text-primary" />
              {dateLabel}
            </span>
            {timeLabel ? (
              <span className="bg-surface-container rounded-DEFAULT px-3 py-1.5 text-xs font-body text-on-surface flex items-center gap-1.5">
                <Clock size={12} className="text-primary" />
                {timeLabel}{endTimeLabel ? ` – ${endTimeLabel}` : ""}
              </span>
            ) : (
              <span className="bg-surface-container rounded-DEFAULT px-3 py-1.5 text-xs font-body text-on-surface-variant flex items-center gap-1.5">
                <Clock size={12} className="text-on-surface-variant" />
                All day
              </span>
            )}
          </div>

          {/* Price + availability */}
          <div className="flex items-baseline gap-3 mb-8">
            <span className="font-headline font-bold text-3xl text-on-surface">
              {event.isFree
                ? "Free"
                : event.price
                  ? event.price.startsWith("$") ? event.price : `$${event.price}`
                  : "See site"}
            </span>
          </div>

          {/* CTA buttons */}
          <div className="flex flex-col gap-3 mb-8">
            {event.sourceUrl && (
              <a
                href={event.sourceUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="btn-primary text-center py-3.5 text-sm flex items-center justify-center gap-2"
              >
                learn more
                <ExternalLink size={13} />
              </a>
            )}
            <ShareButton title={event.title} large />
            <a
              href={`/api/events/${event.id}/ics`}
              className="btn-secondary w-full py-3 text-sm flex items-center justify-center gap-2"
            >
              <CalendarPlus size={14} />
              add to calendar
            </a>
            <InterestButton
              eventId={event.id}
              initialCount={event._count.interests + event.externalInterest}
              variant="detail"
            />
          </div>

          {/* Why we featured it — highlighted one-liner for featured events */}
          {event.featured && event.featuredBlurb && (
            <div className="mb-8 rounded-lg border border-primary/30 bg-primary/5 p-4">
              <div className="flex items-center gap-2 mb-2">
                <Star size={14} className="text-primary shrink-0" fill="currentColor" />
                <h2 className="font-headline font-bold text-sm text-primary lowercase">
                  why we featured it
                </h2>
              </div>
              <p className="font-body text-on-surface text-base leading-relaxed">
                {event.featuredBlurb}
              </p>
            </div>
          )}

          {/* Vibe / description */}
          {event.description && (
            <div className="mb-8">
              <h2 className="font-headline font-bold text-lg text-on-surface lowercase mb-3">
                the vibe
              </h2>
              <p className="font-body text-on-surface-variant text-sm leading-relaxed">
                {event.description}
              </p>
            </div>
          )}
        </div>
      </div>

      {/* Lineup — follow the artists playing (issue #98) */}
      {event.performers.length > 0 && (
        <div className="mb-16">
          <h2 className="font-headline font-bold text-2xl text-on-surface lowercase mb-6">
            lineup
          </h2>
          <div className="flex flex-wrap gap-2">
            {event.performers.map((p) => (
              <span
                key={p}
                className="inline-flex items-center gap-2 bg-surface-container rounded-full pl-3 pr-1.5 py-1"
              >
                <span className="font-body text-sm text-on-surface">{p}</span>
                <FollowButton
                  targetType="ARTIST"
                  targetId={p.toLowerCase()}
                  label={p}
                  isSignedIn={isSignedIn}
                  initialFollowing={isFollowing("ARTIST", p.toLowerCase())}
                />
              </span>
            ))}
          </div>
        </div>
      )}

      {/* The Spot (venue) */}
      {(venueDisplayName || event.venueAddress) && (
        <div className="mb-16">
          <div className="flex items-center gap-3 mb-6">
            <h2 className="font-headline font-bold text-2xl text-on-surface lowercase">
              the spot
            </h2>
            {/* Only normalized venues (with a venueId) are followable — free-text
                venueName can't key a stable follow. */}
            {event.venueId && venueDisplayName && (
              <FollowButton
                targetType="VENUE"
                targetId={event.venueId}
                label={venueDisplayName}
                isSignedIn={isSignedIn}
                initialFollowing={isFollowing("VENUE", event.venueId)}
              />
            )}
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <div className="bg-surface-container rounded-lg p-6">
              <div className="flex items-start gap-3">
                <MapPin size={16} className="text-primary mt-0.5 shrink-0" />
                <div>
                  {tbaCity ? (
                    <>
                      <p className="font-body font-semibold text-primary text-sm">
                        Location TBA
                      </p>
                      <p className="font-body text-on-surface-variant text-xs mt-0.5">
                        {tbaCity} · exact address revealed by the organizer closer
                        to the event.
                      </p>
                    </>
                  ) : (
                    <>
                      {venueDisplayName && (
                        <p className="font-body font-semibold text-on-surface text-sm">
                          {venueDisplayName}
                        </p>
                      )}
                      {event.venueAddress && (
                        <p className="font-body text-on-surface-variant text-xs mt-0.5">
                          {event.venueAddress}
                        </p>
                      )}
                    </>
                  )}
                </div>
              </div>
              {mapsQuery && (
                <a
                  href={`https://maps.google.com/?q=${encodeURIComponent(mapsQuery)}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="mt-4 flex items-center gap-1.5 text-xs font-body text-primary hover:opacity-80 transition-opacity uppercase tracking-wider"
                >
                  <ExternalLink size={11} />
                  open in maps
                </a>
              )}
            </div>

            {/* Mini map — dark Leaflet map matching the rest of the app */}
            {event.venueAddress && event.latitude && event.longitude && (
              <div className="relative rounded-lg overflow-hidden bg-surface-container h-80 sm:h-96">
                <VenueMiniMapWrapper
                  latitude={event.latitude}
                  longitude={event.longitude}
                />
              </div>
            )}
          </div>
        </div>
      )}

      {/* Similar events */}
      {similar.length > 0 && (
        <div>
          <h2 className="font-headline font-bold text-2xl text-on-surface lowercase mb-6">
            similar events
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {similar.map((e: typeof similar[number]) => {
              const cat = e.category ? CATEGORY_COLORS[e.category] : "#3a3a3a";
              return (
                <Link
                  key={e.id}
                  href={`/events/${e.id}`}
                  className="group bg-surface-container rounded-lg overflow-hidden hover:bg-surface-container-high transition-colors"
                >
                  <div className="relative aspect-video bg-surface-container-high">
                    {e.imageUrl ? (
                      <Image
                        src={e.imageUrl}
                        alt={e.title}
                        fill
                        className="object-cover transition-transform duration-500 group-hover:scale-105"
                        sizes="33vw"
                      />
                    ) : (
                      <div
                        className="absolute inset-0"
                        style={{
                          background: `linear-gradient(135deg, ${cat}33, ${cat}11)`,
                        }}
                      />
                    )}
                    <div className="absolute top-2 left-2">
                      <span className="chip text-[0.6rem]">
                        {formatDateShortSF(e.startDate)}
                      </span>
                    </div>
                  </div>
                  <div className="p-4">
                    <p className="font-body font-semibold text-sm text-on-surface line-clamp-2 group-hover:text-primary transition-colors">
                      {e.title}
                    </p>
                    <p className="font-body text-xs text-on-surface-variant mt-1">
                      {e.venueName ?? ""}
                    </p>
                  </div>
                </Link>
              );
            })}
          </div>
        </div>
      )}

      {/* Footer */}
      <footer className="mt-20 pt-8 flex items-center justify-between text-on-surface-variant text-xs font-body">
        <span className="font-headline font-bold text-sm text-on-surface">happening</span>
        <div className="flex items-center gap-4">
          <ReportButton eventId={event.id} />
          <span>
            via{" "}
            <a
              href={event.source.url}
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-on-surface transition-colors"
            >
              {event.source.name}
            </a>
          </span>
        </div>
      </footer>
    </div>
    </>
  );
}
